config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  get '/createbot/intro', to: 'home#createbot_intro'
  get '/createbot/:id', to: 'home#createbotedit', as: 'createbotedit'
  put '/createbot/update/:id', to: 'home#createbotupdate', as: 'createbotupdate'
  get '/selectbot', to: 'home#selectbot'
  #bot editing part
  get '/botsettings/:id', to: 'home#botsettings', as: 'botsettings'
  get '/composemessage/:id', to: 'home#composemessage',as: 'composemessage'
  get '/activatebot/:id', to: 'home#activatebot', as: 'activatebot'
  #bot info part
  get '/statistics/:id', to: 'home#statistics', as: 'statistics'
  get '/testbot/:id', to: 'home#testbot', as: 'testbot'
  resources :bots
  post '/botsetting/reminders/:id', to:'active#botsettings_reminder_create', as:'botsettings_reminder_create'
  put '/botsetting/reminders/edit/:id', to:'active#botsettings_reminder_edit', as:'botsettings_reminder_edit'
  delete '/botsetting/reminders/delete/:id', to:'active#botsettings_reminder_delete', as:'botsettings_reminder_delete'
  put 'active/:id', to: 'active#updateactive', as: 'bot_active'
  #compose message
  get 'triggerphrase/edit/:id' , to: 'active#triggerphraseedit' , as: 'triggerphraseedit'
  get 'triggerphrase/confirm/:id' , to: 'active#triggerphraseconfirm' , as: 'triggerphraseconfirm'
  post 'triggerphrase/create/:id' , to: 'active#triggerphrasecreate' , as: 'triggerphrasecreate'
  delete 'triggerphrase/delete/:id/:botid' , to: 'active#triggerphrasedelete' , as: 'triggerphrasedelete'
  #nodes
  post 'nodes/create/:botid/:parentid/:nodetype' , to: 'nodes#create' , as: 'nodescreate'
  delete 'nodes/destroy/:id' , to: 'nodes#destroy' , as: 'nodes_destroy'
  post 'nodes/message_create' , to: 'nodes#message_create' , as: 'nodes_message_create'
  delete 'nodes/message_delete/:msg_id/:bot_id/:node_id', to: 'nodes#message_delete', as: 'nodes_message_delete'
  put 'nodes/update_options/:bot_id/:node_id', to: 'nodes#update', as: 'nodes_update_options'
  get 'nodes/expand/:bot_id/:node_id', to: 'nodes#expand', as: 'nodes_expand'
  get 'nodes/number_of_nodes_increment/:node_id', to: 'nodes#increment', as: 'number_of_nodes_increment'
  get 'nodes/number_of_nodes_decrement/:node_id', to: 'nodes#decrement', as: 'number_of_nodes_decrement'
  post 'nodes/add_numberof_nodes/:botid/:parentid/:nodetype', to: 'nodes#add_number_of_nodes', as: 'add_number_of_nodes'
  delete 'nodes/usermessage_node_delete/:id/:position', to: 'nodes#usermessage_node_delete', as: 'usermessage_node_delete'
  get 'nodes/define_nodes/:id', to: 'nodes#define_nodes', as: 'define_nodes'
  put 'nodes/usermessage_options_form/:id', to: 'nodes#usermessage_options_form', as: 'usermessage_options_form'
  get 'nodes/usermessage_name_edit/:id', to: 'nodes#usermessage_name_edit', as: 'usermessage_name_edit'
  put 'nodes/usermessage_name_update/:id', to: 'nodes#usermessage_name_update', as: 'usermessage_name_update'
  get 'nodes/botmessage_name_edit/:id', to: 'nodes#botmessage_name_edit', as: 'botmessage_name_edit'
  put 'nodes/botmessage_name_update/:id', to: 'nodes#botmessage_name_update', as: 'botmessage_name_update'
  get 'nodes/usermessage/expand/:id', to: 'nodes#usermessage_expand', as: 'usermessage_expand'
  post 'nodes/usermessage/messages_create', to: 'nodes#usermessage_messages_create', as: 'usermessage_messages_create'
  delete 'nodes/usermessage_message_delete/:msg_id/:bot_id/:node_id', to: 'nodes#usermessage_message_delete', as: 'usermessage_message_delete'
  put 'nodes/toggle_exit_message/:id', to: 'nodes#toggle_exit_message', as: 'toggle_exit_message'
  put 'nodes/toggle_transfer_to_agent_message/:id', to: 'nodes#toggle_transfer_to_agent_message', as: 'toggle_transfer_to_agent_message'
  post 'nodes/error_message_define_node', to: 'nodes#error_message_define_node', as: 'error_message_define_node'
  post 'nodes/error_node_message_save/:id/:message_id', to: 'nodes#error_node_message_save', as: 'error_node_message_save'
  get 'nodes/usermessage/error_message_expand_icon/:node_id', to: 'nodes#error_message_expand_icon', as: 'error_message_expand_icon'
  delete 'nodes/usermessage/error_message_attempt_delete/:message_id', to: 'nodes#error_message_attempt_delete', as: 'error_message_attempt_delete'
  get 'nodes/usermessage/error_node_save/:node_id', to: 'nodes#error_node_save', as: 'error_node_save'
  get 'nodes/usermessage/add_another_error_attempt/:node_id', to: 'nodes#error_node_add_another_error_attempt', as: 'error_node_add_another_error_attempt'
  get 'nodes/usermessage/error_node_editing_message/:message_id', to: 'nodes#error_node_editing_message', as: 'error_node_editing_message'
  get 'nodes/usermessage/error_node_delete_icon_for_new_attempt/:error_node_id', to: 'nodes#error_node_delete_icon_for_new_attempt', as:'error_node_delete_icon_for_new_attempt'
  post 'nodes/botresponse/nodes_message_attach_media', to: 'nodes#nodes_message_attach_media', as: 'nodes_message_attach_media'
  get 'nodes/botresponse/add_a_new_text_message_button/:node_id', to: 'nodes#add_a_new_text_message_button', as:'add_a_new_text_message_button'
  post 'nodes/botresponse/nodes_message_attach_media_video', to: 'nodes#nodes_message_attach_media_video', as:'nodes_message_attach_media_video'
  post 'nodes/botresponse/nodes_message_attach_media_pdf', to: 'nodes#nodes_message_attach_media_pdf', as:'nodes_message_attach_media_pdf'
  get 'nodes/ckeditor/text_messages/edit_icon/:node_id/:bot_id/:message_id', to:'nodes#ckeditor_text_messages_edit_icon', as: 'ckeditor_text_messages_edit_icon'
  post 'nodes/ckeditor/text_messages/update/:node_id/:bot_id/:message_id', to: 'nodes#ckeditor_text_messages_update', as: 'ckeditor_text_messages_update'
  get 'nodes/ckeditor/nodes_message_delete_text_area/:node_id', to: 'nodes#nodes_message_delete_text_area', as: 'nodes_message_delete_text_area'
end

app/models/node.rb
class Node < ApplicationRecord
	belongs_to :bot
	has_many :messages, dependent: :destroy
	acts_as_tree order: "name"
	extend ActsAsTree::TreeWalker
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
	def create
		@bot = Bot.find(params[:botid])
		@node = Node.create(node_type: params[:nodetype], bot_id: params[:botid], parent_id: params[:parentid])
		@parent_id = params[:parentid]
		if Node.where(bot_id: @bot.id, node_type: "bot").count == 1
			@node.update(name: "Bot_response_1")
		else
			last_name = Node.where(bot_id: @bot.id, node_type: "bot").order(:id).second_to_last().name
			new_last_name = last_name[0..12]
			last_number = last_name[13..-1].to_i
			last_number = last_number + 1
			last_number = last_number.to_s
			new_last_name = new_last_name + last_number
			@node.update(name: new_last_name)	
		end
		respond_to do |format|
		    format.js
	  	end
	end

	def update
		@bot = Bot.find(params[:bot_id])
		@node = Node.find(params[:node_id])
		@parent_id = @node.parent_id
		@node.update(set_next_action: params[:set_next_action][:set_next_action], 
			exit_message: params[:set_next_action][:exit_bot_message], 
			transfer_to_agent_message: params[:set_next_action][:transfer_to_agent_message],
			link_to_node_message: params[:set_next_action][:link_to_node_message],
			link_to_node: params[:set_next_action][:link_to_node])
		respond_to do |format|
		    format.js
	  	end
	end

	def destroy
		@node = Node.find(params[:id])
		@node_for_id = Node.find(params[:id])
		@parent_id = @node.parent_id
		@node.destroy
		@node= nil;
		respond_to do |format|
		    format.js
	  	end
	end

	def message_create
		@bot = Bot.find(params[:message][:bot_id])
		@node = Node.find(params[:message][:node_id])
		@parent_id = @node.parent_id
		@message = Message.create(params.require(:message).permit(:text_messages, :node_type, :bot_id, :node_id, :message_type))
		respond_to do |format|
		    format.js
	  	end
	end

	def nodes_message_attach_media
		@node = Node.find(params[:attach_message][:node_id])
		@bot = Bot.find(@node.bot_id)
		@parent_id = @node.parent_id
		@message = Message.new(params.require(:attach_message).permit(:image, :node_id, :node_type, :bot_id, :message_type))
		if @message.save
			respond_to do |format|
			    format.js 
		  	end
		else
		 	respond_to do |format|
			    format.js {flash.now[:alert] = "Upload only images"}
		  	end
		end  	
	end

	def nodes_message_attach_media_video
		@node = Node.find(params[:attach_video_message][:node_id])
		@bot = Bot.find(@node.bot_id)
		@parent_id = @node.parent_id
		@message = Message.new(params.require(:attach_video_message).permit(:video, :node_id, :node_type, :bot_id, :message_type))
		if @message.save
			respond_to do |format|
			    format.js 
		  	end
		else
		 	respond_to do |format|
			    format.js {flash.now[:alert] = "Upload only videos"}
		  	end
		end
	end

	def nodes_message_attach_media_pdf
		@node = Node.find(params[:attach_pdf_message][:node_id])
		@bot = Bot.find(@node.bot_id)
		@parent_id = @node.parent_id
		@message = Message.new(params.require(:attach_pdf_message).permit(:pdf, :node_id, :node_type, :bot_id, :message_type))
		if @message.save
			respond_to do |format|
			    format.js 
		  	end
		else
		 	respond_to do |format|
			    format.js {flash.now[:alert] = "Upload only PDF"}
		  	end
		end
	end

	def message_delete
		@bot = Bot.find(params[:bot_id])
		@node = Node.find(params[:node_id])
		@parent_id = @node.parent_id
		@message = Message.find(params[:msg_id])
		@message.destroy
		respond_to do |format|
		    format.js
	  	end
	end

	def expand
		@bot = Bot.find(params[:bot_id])
		@node = Node.find(params[:node_id])
		respond_to do |format|
		    format.js
	  	end
	end

	def increment
		@node = Node.find(params[:node_id])
		respond_to do |format|
		    format.js
	  	end
	end

	def decrement
		@node = Node.find(params[:node_id])
		respond_to do |format|
		    format.js
	  	end
	end

	def add_number_of_nodes
		@bot = Bot.find(params[:botid])
		number = (params[:number_of_nodes][:number]).to_i
		for i in (1..number)
			@node = Node.create(node_type: params[:nodetype], bot_id: params[:botid], parent_id: params[:parentid])
		end
		@node = Node.find(params[:parentid]) 
		respond_to do |format|
		    format.js
	  	end
	end

	def usermessage_node_delete
	 	@node = Node.find(params[:id])
	 	@position = params[:position]
	 	if @position == "expanded"
	 		@height_diff = 405;
	 	elsif @position == "define"
	 		@height_diff = 52; 
	 	elsif @position == "compressed"
	 		@height_diff = 108;
	 	end
	 	
	 	@parent_id = @node.parent_id
	 	@node.destroy
	 	@node = Node.find(@parent_id)
	 	@number_of_children = 0 

	 	for i in @node.children
	 		@number_of_children = @number_of_children + 1
	 	end

		respond_to do |format|
		    format.js
	  	end
	end


	def define_nodes
		@id = params[:id]
		@child = Node.find(@id)
		@node = Node.find(@child.parent_id)
		respond_to do |format|
		    format.js
	  	end
	end

	def usermessage_options_form
		@id = params[:id]
		@child = Node.find(params[:id])
		@node = Node.find(@child.parent_id)
		@child.update(user_input_type: params[:child_options][:user_input_type])
		respond_to do |format|
		    format.js
	 	end
	end

	def usermessage_name_edit
		@id = params[:id]
		respond_to do |format|
		    format.js
	 	end
	end

	def usermessage_name_update
		@id = params[:id]
		@child = Node.find(params[:id])
		@child.update(name: params[:name_edit][:name])
		respond_to do |format|
		    format.js
	 	end
	end

	def botmessage_name_edit
		@id = params[:id]
		respond_to do |format|
		    format.js
	 	end
	end

	def botmessage_name_update
		@id = params[:id]
		@node = Node.find(params[:id])
		@node.update(name: params[:name_edit][:name])
		respond_to do |format|
		    format.js
	 	end
	end

	def usermessage_expand
		@id = params[:id]
		@child = Node.find(@id)
		@node = Node.find(@child.parent_id)
		respond_to do |format|
		    format.js
	 	end
	end

	def usermessage_messages_create
		@child = Node.find(params[:messages][:node_id])
		@message = Message.create(params.require(:messages).permit(:text_messages, :node_type, :bot_id, :node_id))
		respond_to do |format|
		    format.js
	  	end
	end

	def usermessage_message_delete
		@bot = Bot.find(params[:bot_id])
		@child = Node.find(params[:node_id])
		@message = Message.find(params[:msg_id])
		@message.destroy
		respond_to do |format|
		    format.js
	  	end
	end

	def toggle_exit_message
		@node = Node.find(params[:id])
		@parent_id = @node.parent_id
		@bot_id= @node.bot_id
		@bot = Bot.find(@bot_id)
		  if @node.toggle_exit_message == true
		    @node.update(toggle_exit_message: false)
		    @toggle_exit_message_state = false
		    respond_to do |format|
			   format.js
		  	end
		  else
		  	@node.update(toggle_exit_message: true)
		    @toggle_exit_message_state = true
		    respond_to do |format|
			   format.js
		  	end
		  end
	end

	def toggle_transfer_to_agent_message
		@node = Node.find(params[:id])
		@parent_id = @node.parent_id
		@bot_id= @node.bot_id
		@bot = Bot.find(@bot_id)
		  if @node.toggle_transfer_to_agent_message == true
		    @node.update(toggle_transfer_to_agent_message: false)
		    @toggle_transfer_to_agent_message_state = false
		    respond_to do |format|
			   format.js
		  	end
		  else
		  	@node.update(toggle_transfer_to_agent_message: true)
		    @toggle_transfer_to_agent_message_state = true
		    respond_to do |format|
			   format.js
		  	end
		  end
	end

	def error_message_define_node
		@parent_id = params[:error_message_define][:parent_id]
		@error_node = Node.create(params.require(:error_message_define).permit(:node_type, :bot_id, :parent_id))
		@node = Node.find(@error_node.parent_id)
		@bot = Bot.find(@node.bot_id)
		respond_to do |format|
		   format.js
	  	end
	end

	def error_node_message_save
		@error_node = Node.find(params[:id])
		@parent = Node.find(@error_node.parent_id)
		@node = @parent
		@bot = Bot.find(@node.bot_id)
		if params[:message_id] == "default"
			@message = Message.create(node_type: "error", bot_id: @error_node.bot_id, node_id: @error_node.id, error_node: params[:error_node][:error_node],
				error_node_message: params[:error_node][:error_node_message], error_node_link_to_message: params[:error_node][:error_node_link_to_message],
				error_node_exit_message: params[:error_node][:error_node_exit_message], error_node_transfer_to_agent_message: params[:error_node][:error_node_transfer_to_agent_message],
				error_node_link_to_node: params[:error_node][:error_node_link_to_node])
		else
			@message = Message.find(params[:message_id])
			@message.update(error_node: params[:error_node][:error_node],
				error_node_message: params[:error_node][:error_node_message], error_node_link_to_message: params[:error_node][:error_node_link_to_message],
				error_node_exit_message: params[:error_node][:error_node_exit_message], error_node_transfer_to_agent_message: params[:error_node][:error_node_transfer_to_agent_message],
				error_node_link_to_node: params[:error_node][:error_node_link_to_node])
		end
		respond_to do |format|
		   format.js
	  	end
	end

	def error_message_expand_icon
		@node = Node.find(params[:node_id])
		@error_node = Node.where(node_type: "error", parent_id: @node.id).first
		respond_to do |format|
		   format.js
	  	end
	end

	def error_message_attempt_delete
		@error_message = Message.find(params[:message_id])
		@bot = Bot.find(@error_message.bot_id)
		@error_node = Node.find(@error_message.node_id)
		@node = Node.find(@error_node.parent_id)
		@error_message.destroy
		respond_to do |format|
		   format.js
	  	end
	end

	def error_node_save
		@error_node = Node.find(params[:node_id])
		@parent = Node.find(@error_node.parent_id)
		@node = @parent
		@bot = Bot.find(@node.bot_id)
		respond_to do |format|
		   format.js
	  	end
	end

	def error_node_add_another_error_attempt
		@error_node = Node.find(params[:node_id])
		@bot = Bot.find(@error_node.bot_id)
		@node = Node.find(@error_node.parent_id)
		respond_to do |format|
		   format.js
	  	end
	end

	def  error_node_editing_message
		@message = Message.find(params[:message_id])
		@error_node = Node.find(@message.node_id)

app/views/home/edit/nodes/_botmessages_box_after_text_area.html.erb
<%if @node%> 
	<% text_area_form_hide_or_show = "text_area_form_hide_or_show_" +  (@node.id).to_s %>

	<% botresponses_messages_area_text_area = "botresponses_messages_area_text_area_" + (@node.id).to_s%>
	<% botresponses_text_message_node_type = "botresponses_text_message_node_type_" + (@node.id).to_s%>
	<% botresponses_text_message_bot_id = "botresponses_text_message_bot_id_" + (@node.id).to_s%>
	<% botresponses_text_message_message_type = "botresponses_text_message_message_type_" + (@node.id).to_s%>
	<% botresponses_text_message_node_id = "botresponses_text_message_node_id_" + (@node.id).to_s%>
	<% delete_text_message_text_area = "delete_text_message_text_area_" + (@node.id).to_s%>

	<script src = "/assets/ckeditor/ckeditor.js" > </script>

	<div class="text-center mx-auto hide" id= <%= text_area_form_hide_or_show%>>
	<%= form_with scope: :message, url: nodes_message_create_path, method: :post,  remote: true do |f| %>
		<div class="text-center botresponses_messages_area_full">
			<%= text_area :message, :text_messages, cols: 30, rows: 4, id: botresponses_messages_area_text_area %>
			<%= f.text_field :node_type, value: "bot", class: "hide", id: botresponses_text_message_node_type%>
			<%= f.text_field :bot_id, value: @bot.id , class: "hide", id: botresponses_text_message_bot_id%>
			<%= f.text_field :message_type, value: "text" , class: "hide", id: botresponses_text_message_message_type%>
			<% if Node.where(bot_id: @bot.id, parent_id: parent_id).first%>
			<%= f.text_field :node_id, value: @node.id, class: "hide", id: botresponses_text_message_node_id%>
			<% end %>
			
			<div class="row mb-1 ml-2">
				<div class="col-4 mt-2">
					<%= link_to image_tag('dustbin.png', size: "12", class: "styling_the_delete_position_text_area"), nodes_message_delete_text_area_path(@node.id),id: delete_text_message_text_area, method: :get ,remote: true, class: ""%>
				</div>
				<div class="col-8" style="text-align: right;">
					<%= f.submit "Add", value: "Add", class: "btn btn-outline-secondary btn-sm mr-4", style: "height: 30px; margin-top: 5px; text-align: right;"%>
				</div>
			</div>
		</div>
	<% end %>	
	</div>

	<script type="text/javascript">		
	    editor = CKEDITOR.replace('<%= botresponses_messages_area_text_area %>');
	    editor.setData('<p></p>'); 
	</script>

<%end%>

app/views/home/edit/nodes/_botmessages_box_before.html.erb
<% botresponses_box_before = "botresponses_box_before_" + (parent_id).to_s %>
<div class="botresponses_box_before row" id="<%= botresponses_box_before %>">
	<div class="col-10 row">
		<%= image_tag('chatbot.JPG', size: "25", class: "rounded-circle mr-3 ml-3 mt-2")%>
		<div class="botresponses_text">Bot Response</div>
	</div>
	<div class="col-2">
		<%= link_to 'Add', nodescreate_path(@bot.id, parent_id , "bot"), class: "btn btn-dark btn-sm", method: :post , remote: true, style: "height: 35px; margin-top: 5px;" %>
	</div>
</div>

app/views/home/edit/nodes/_botmessages_box_compressed.html.erb
<% @node = Node.where(bot_id: @bot.id, parent_id: parent_id).first%>
<%if @node%>
	<% botresponses_box_compressed = "botresponses_box_compressed_" + (@node.id).to_s%>
	<% botmessages_previous_compressed = "botmessages_previous_compressed_" + (@node.id).to_s%>
	<% botmessage_compressed_name = "botmessage_compressed_name_" + (@node.id).to_s%>
<%end%>

<div class="botresponses_box_after hide  mb-4" id="<%= botresponses_box_compressed %>">
	<div class="row">
		<div class="col-9 row mb-2">
			<div class="col-2 mr-2">
				<%= image_tag('chatbot.JPG', size: "25", class: "rounded-circle mr-1 ml-2 mt-2")%>
			</div>
			<%if @node%>			
				<div class="botresponses_text col-8 ml-1" id= <%= botmessage_compressed_name%>>
					<%= render 'home/edit/nodes/botmessages_name_field', node: @node, edit_tag: false%>
				</div>
			<% end %>
		</div>
		<div class="col-3 text-center">
			<% if Node.where(bot_id: @bot.id, parent_id: parent_id).first%>
			<%= link_to image_tag('dustbin.png', size: "15", class: "mt-2 mr-2"), nodes_destroy_path(@node.id), method: :delete , remote: true, data: { confirm: "Are you sure that you want to delete this node? This will delete all the children nodes attached to it. You can edit the current node, if you wanted to."}%>
			<%= link_to image_tag('expand.png', size: "15", class: "mt-2"), nodes_expand_path(@bot.id, @node.id), remote: true%>
			<% end %>
		</div>
	</div>

	<div class="card_divider mb-2"></div>
	<!-- added messages -->
	<div class="mb-4 pb-2" id="<%= botmessages_previous_compressed %>">
		<%= render 'home/edit/nodes/botmessages_previous', delete_button: false, parent_id: parent_id%>
	</div>
</div>

app/views/home/edit/nodes/_triggerphrasesform.html.erb
<div class="ml-3 hide" id="triggerphrase_add_a_new_phrase">
	<%= form_with scope: :triggerphrase, url: triggerphrasecreate_path(@bot.id), method: :post, remote: true do |f| %>
    <span class="mx-auto text-center" style="width: 300px; " >
      <%= f.text_field :triggerphrase, id: "addtriggerphrasefield" ,class: "addtriggerphrasefield", placeholder: "Add a new phrase", remote: true%> 
    </span>
    <span class="form-group mx-auto text-center mt-4" style="width: 300px;">
      <%= f.submit "Add" ,value: "Add", class: "btn btn-sm btn-outline-success ml-2", remote: true%>
    </span>
  <% end %>
</div>

app/views/home/edit/nodes/_usermessages_compressed.html.erb
<% compressed_define_id = "compressed_define_nodes_id_" + child.id.to_s %>
<% compressed_define_name_id = "compressed_define_nodes_name_id_" + child.id.to_s %>
<% usermessage_message_compressed_partial_id = "usermessage_message_compressed_partial_id_" + child.id.to_s%>
<% usermessage_compressed_node_expand_icon = "usermessage_compressed_node_expand_icon_" + child.id.to_s%>
<% connector_green_link_compressed_id = "connector_green_link_compressed_id_" + child.id.to_s%>

<div class="row mb-2 hide" id= <%= compressed_define_id%> >
	<div class="connector_black_link"></div>
	<div class="usermessage_before">
		<div class="row Initial-Message-from-Customer", style="font-size: 15px;">
			<div class="col-9" id= <%= compressed_define_name_id%>>
				<%= render 'home/edit/nodes/usermessages_compressed_name', child: child%>	
			</div>
			<div class="col-1">
				<%= link_to image_tag('dustbin.png', size: "15"), usermessage_node_delete_path(child.id, "compressed"), method: :delete, remote: true, data: { confirm: "Are you sure that you want to delete this node? This will delete all the children nodes attached to it. You can edit the current node, if you wanted to."}%>
			</div>
			<div class="col-1">	
				<%= link_to image_tag('expand.png', size: "14"), usermessage_expand_path(child.id), id: usermessage_compressed_node_expand_icon , remote: true, class: ""%>
			</div>			
		</div>
		<div class="card_divider mb-2"></div>
		<div class="row triggerphrases_partial ml-3", style="overflow-y: auto;overflow-x: hidden; height: 50px; width: 280px;" >
				<div id= <%= usermessage_message_compressed_partial_id%>>
					<%= render 'home/edit/nodes/usermessages_message_previous', child: child, delete_button: false%>
				</div>			
		</div>
	</div>
	<div class="connector_green_circle "></div>
	<div class="connector_green_link", id="<%= connector_green_link_compressed_id %>"></div>
</div>

app/views/home/edit/nodes/_usermessages_compressed_name.html.erb
<%if child.name%>
	<%= child.name%>
<%else%>
	User Message
<%end%>

app/views/home/edit/nodes/_usermessages_define_node.html.erb
<% define_id = "define_nodes_id_" + child.id.to_s %>
<% connector_green_link_define_id = "connector_green_link_define_id_" + child.id.to_s%>
<div class="row mb-2" id= <%= define_id%> >
	<div class="connector_black_link"></div>
	<div class="usermessage_white_box">
		<div class="row">
			<div class="col-1 text-center mt-2 ml-2">
				<%= image_tag('greenflash.JPG', size: "14", class: "rounded-circle")%>
			</div>
			<div class="col-4 mt-2", style="padding-right: 5px;">
				Define node
			</div>
			<div class="col-6 mt-2 ml-2", style="padding-left: 5px;">
				<%= form_with scope: :define_node, url: define_nodes_path(child.id), method: :get, remote: true do |f| %>
			    <span class=" text-right ml-5">
				  	<%= link_to image_tag('dustbin.png', size: "10"), usermessage_node_delete_path(child.id, "define"), method: :delete, remote: true, data: { confirm: "Are you sure that you want to delete this node? This will delete all the children nodes attached to it. You can edit the current node, if you wanted to."}%>
				</span>
				<span class="text-center ml-3">
					<%= f.submit "Define", value: "Define", class: "usermessage_add_button", remote: true%>
				</span>
			  	<% end %>
			</div>
		</div>
	</div>
	<div class="connector_green_circle "></div>
	<div class="connector_green_link", id="<%= connector_green_link_define_id %>"></div>
</div>

app/views/home/edit/nodes/_usermessages_error_define_node.html.erb
<div class="row">
	<div class="col-1 text-center mt-2 ml-2">
		<%= image_tag('redflash.JPG', size: "14", class: "rounded-circle")%>
	</div>
	<div class="col-6 mt-2", style="padding-right: 5px;">
		Error Response
	</div>
	<% error_message_define_node_type_id = 'error_message_define_node_type_id_' + (@node.id).to_s%>
	<% error_message_define_bot_id = 'error_message_define_bot_id_' + (@node.id).to_s%>
	<% error_message_define_parent_id = 'error_message_define_parent_id_' + (@node.id).to_s%>
	<div class="col-4 mt-2 ml-2", style="padding-left: 5px;">
		<%= form_with scope: :error_message_define, url: error_message_define_node_path, method: :post, remote: true do |f| %>
			<%= f.text_field :node_type, value: "error",id: error_message_define_node_type_id, class: "hide"%>
			<%= f.text_field :bot_id, value: @bot.id,id: error_message_define_bot_id, class: "hide"%>
			<%= f.text_field :parent_id, value: @node.id,id: error_message_define_parent_id, class: "hide"%>
	        <span class="text-center ml-4">
				<%= f.submit "Define", value: "Define", class: "usermessage_error_button", local: true%>
		    </span>
	    <% end %>
	</div>
</div>