config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  get '/createbot/intro', to: 'home#createbot_intro'
  get '/createbot/:id', to: 'home#createbotedit', as: 'createbotedit'
  put '/createbot/update/:id', to: 'home#createbotupdate', as: 'createbotupdate'
  get '/selectbot', to: 'home#selectbot'
  #bot editing part
  get '/botsettings/:id', to: 'home#botsettings', as: 'botsettings'
  get '/composemessage/:id', to: 'home#composemessage',as: 'composemessage'
  get '/activatebot/:id', to: 'home#activatebot', as: 'activatebot'
  #bot info part
  get '/statistics/:id', to: 'home#statistics', as: 'statistics'
  get '/testbot/:id', to: 'home#testbot', as: 'testbot'
  resources :bots
  post '/botsetting/reminders/:id', to:'active#botsettings_reminder_create', as:'botsettings_reminder_create'
  put '/botsetting/reminders/edit/:id', to:'active#botsettings_reminder_edit', as:'botsettings_reminder_edit'
  delete '/botsetting/reminders/delete/:id', to:'active#botsettings_reminder_delete', as:'botsettings_reminder_delete'
  put 'active/:id', to: 'active#updateactive', as: 'bot_active'
  #compose message
  get 'triggerphrase/edit/:id' , to: 'active#triggerphraseedit' , as: 'triggerphraseedit'
  get 'triggerphrase/confirm/:id' , to: 'active#triggerphraseconfirm' , as: 'triggerphraseconfirm'
  post 'triggerphrase/create/:id' , to: 'active#triggerphrasecreate' , as: 'triggerphrasecreate'
  delete 'triggerphrase/delete/:id/:botid' , to: 'active#triggerphrasedelete' , as: 'triggerphrasedelete'
  #nodes
  post 'nodes/create/:botid/:parentid/:nodetype' , to: 'nodes#create' , as: 'nodescreate'
  delete 'nodes/destroy/:id' , to: 'nodes#destroy' , as: 'nodes_destroy'
  post 'nodes/message_create' , to: 'nodes#message_create' , as: 'nodes_message_create'
  delete 'nodes/message_delete/:msg_id/:bot_id/:node_id', to: 'nodes#message_delete', as: 'nodes_message_delete'
  put 'nodes/update_options/:bot_id/:node_id', to: 'nodes#update', as: 'nodes_update_options'
  get 'nodes/expand/:bot_id/:node_id', to: 'nodes#expand', as: 'nodes_expand'
  get 'nodes/number_of_nodes_increment/:node_id', to: 'nodes#increment', as: 'number_of_nodes_increment'
  get 'nodes/number_of_nodes_decrement/:node_id', to: 'nodes#decrement', as: 'number_of_nodes_decrement'
  post 'nodes/add_numberof_nodes/:botid/:parentid/:nodetype', to: 'nodes#add_number_of_nodes', as: 'add_number_of_nodes'
  delete 'nodes/usermessage_node_delete/:id/:position', to: 'nodes#usermessage_node_delete', as: 'usermessage_node_delete'
  get 'nodes/define_nodes/:id', to: 'nodes#define_nodes', as: 'define_nodes'
  put 'nodes/usermessage_options_form/:id', to: 'nodes#usermessage_options_form', as: 'usermessage_options_form'
  get 'nodes/usermessage_name_edit/:id', to: 'nodes#usermessage_name_edit', as: 'usermessage_name_edit'
  put 'nodes/usermessage_name_update/:id', to: 'nodes#usermessage_name_update', as: 'usermessage_name_update'
  get 'nodes/botmessage_name_edit/:id', to: 'nodes#botmessage_name_edit', as: 'botmessage_name_edit'
  put 'nodes/botmessage_name_update/:id', to: 'nodes#botmessage_name_update', as: 'botmessage_name_update'
  get 'nodes/usermessage/expand/:id', to: 'nodes#usermessage_expand', as: 'usermessage_expand'
  post 'nodes/usermessage/messages_create', to: 'nodes#usermessage_messages_create', as: 'usermessage_messages_create'
  delete 'nodes/usermessage_message_delete/:msg_id/:bot_id/:node_id', to: 'nodes#usermessage_message_delete', as: 'usermessage_message_delete'
  put 'nodes/toggle_exit_message/:id', to: 'nodes#toggle_exit_message', as: 'toggle_exit_message'
  put 'nodes/toggle_transfer_to_agent_message/:id', to: 'nodes#toggle_transfer_to_agent_message', as: 'toggle_transfer_to_agent_message'
  post 'nodes/error_message_define_node', to: 'nodes#error_message_define_node', as: 'error_message_define_node'
  post 'nodes/error_node_message_save/:id/:message_id', to: 'nodes#error_node_message_save', as: 'error_node_message_save'
  get 'nodes/usermessage/error_message_expand_icon/:node_id', to: 'nodes#error_message_expand_icon', as: 'error_message_expand_icon'
  delete 'nodes/usermessage/error_message_attempt_delete/:message_id', to: 'nodes#error_message_attempt_delete', as: 'error_message_attempt_delete'
  get 'nodes/usermessage/error_node_save/:node_id', to: 'nodes#error_node_save', as: 'error_node_save'
  get 'nodes/usermessage/add_another_error_attempt/:node_id', to: 'nodes#error_node_add_another_error_attempt', as: 'error_node_add_another_error_attempt'
  get 'nodes/usermessage/error_node_editing_message/:message_id', to: 'nodes#error_node_editing_message', as: 'error_node_editing_message'
  get 'nodes/usermessage/error_node_delete_icon_for_new_attempt/:error_node_id', to: 'nodes#error_node_delete_icon_for_new_attempt', as:'error_node_delete_icon_for_new_attempt'
  post 'nodes/botresponse/nodes_message_attach_media', to: 'nodes#nodes_message_attach_media', as: 'nodes_message_attach_media'
  get 'nodes/botresponse/add_a_new_text_message_button/:node_id', to: 'nodes#add_a_new_text_message_button', as:'add_a_new_text_message_button'
  post 'nodes/botresponse/nodes_message_attach_media_video', to: 'nodes#nodes_message_attach_media_video', as:'nodes_message_attach_media_video'
  post 'nodes/botresponse/nodes_message_attach_media_pdf', to: 'nodes#nodes_message_attach_media_pdf', as:'nodes_message_attach_media_pdf'
  get 'nodes/ckeditor/text_messages/edit_icon/:node_id/:bot_id/:message_id', to:'nodes#ckeditor_text_messages_edit_icon', as: 'ckeditor_text_messages_edit_icon'
  post 'nodes/ckeditor/text_messages/update/:node_id/:bot_id/:message_id', to: 'nodes#ckeditor_text_messages_update', as: 'ckeditor_text_messages_update'
  get 'nodes/ckeditor/nodes_message_delete_text_area/:node_id', to: 'nodes#nodes_message_delete_text_area', as: 'nodes_message_delete_text_area'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def landing
	end
	
	def welcome
	end

	def createbot_intro
	end

	def createbotedit
		@id = params[:id]
		@bot = Bot.find_by(id: @id)
		respond_to do |format|
			format.js
		end
	end


	def createbotupdate
		@id = params[:id]
		@bot = Bot.find_by(id: @id)
		@bot.update(params.require(:bot).permit(:name))
	 	respond_to do |format|
			format.js
		end
	end

	def selectbot
	end

	def botsettings
		@id = params[:id]
		@bot = Bot.find_by(id: @id)
		@userbots= Bot.where(user_id: current_user.id)
	end

	def composemessage
		@id = params[:id]
		@bot = Bot.find(@id)
		
	end

	def activatebot
		@id = params[:id]
		@bot = Bot.find(@id)
	end

	def statistics
		@id = params[:id]
		@bot = Bot.find(@id)
	end
	
	def testbot
		@id = params[:id]
		@bot = Bot.find(@id)
	end
end

app/views/home/activatebot.html.erb
<%= render 'layouts/navbar'%>
<%= render 'layouts/messages'%>
<div class="container">
	<!-- top page navigation -->
	<div class="row mt-1">
		<div class="col-1">
		</div>
		<div class="col-10 ">
			<div class="row">
				<div class="col-2">
					<%= link_to '← Go Back', root_path, class: "custom_link"%>						
				</div>
				
				<div class="col-3 text-center">
					Bot settings
				</div>
				<div class="col-3 text-center">
					Compose Message
				</div>
				<div class="col-3 text-center">
					Activate Bot
				</div>
				<div class="col-1">
				</div>
			</div>

			<div class="row">
				<div class="col-3">
				</div>
				<div class="col-1 text-center">
					<%= link_to image_tag('radiooff.png', size: "15", class: "rounded-circle"), botsettings_path(@id), class: "custom_link"%>
				</div>
				<div class="col-2 text-center">
					<svg height="20" width="300">
					  <line x1="0" y1="15" x2="150" y2="15" style="stroke:rgb(0,0,0);stroke-width:1" />
					</svg>
				</div>
				<div class="col-1 text-center">
					<%= link_to image_tag('radiooff.png', size: "15", class: "rounded-circle"), composemessage_path(@id), class: "custom_link"%>
				</div>
				<div class="col-2 text-center">
					<svg height="20" width="300">
					  <line x1="0" y1="15" x2="150" y2="15" style="stroke:rgb(0,0,0);stroke-width:1" />
					</svg>
				</div>
				<div class="col-1 text-center">
					<%= link_to image_tag('radioon.png', size: "15", class: "rounded-circle"), activatebot_path(@id), class: "custom_link"%>
				</div>
				<div class="col-2">
				</div>
			</div>
		</div>
		<div class="col-1">
		</div>	
	</div>

	<!-- main content -->
	<div class="row mt-4">
		<div class="col-1">
		</div>

		<div class="col-10 rowheight_three border bg-white">
			<%= render 'home/edit/activatebot_main'%>
		</div>

		<div class="col-1">
		</div>
	</div>
</div>

app/views/home/botsettings.html.erb
<%= render 'layouts/navbar_main'%>
<%= render 'layouts/navbar_navigation_botsettings'%>
<%= render 'layouts/messages'%>
<div class="container">
	<!-- main content -->
	<div class="row mt-4">
    <!-- left content -->
  
		<div class="col-4 rowheight_three bg-white botsettings_border hide" id="botsettings_startsetup">
      <%= render 'home/edit/botsettings_startsetup'%>
		</div>
    <div class="col-4 rowheight_three bg-white botsettings_border" id="botsettings_startsetup_edit">
       <%= render 'home/edit/botsettings_startsetup_edit'%>
    </div>
    <!-- actual form -->
		<div class="col-8 rowheight_three" id="actualform">
      <%= render 'home/edit/botsettings_main'%>
    </div>
	</div>
</div>

<script type="text/javascript">
      // show form
      <% if (@bot.phone == nil && @bot.language == nil && @bot.initconv == nil && @bot.triggerpoint==nil  && @bot.rebootconv==nil && @bot.active==nil)%>
       document.getElementById('botsettings_startsetup').classList.remove('hide');        
       document.getElementById('botsettings_startsetup_edit').classList.add('hide');        
       document.getElementById('actualform').classList.add('hide');        
      <% end %>
      
      document.getElementById('startsetup').onclick = function() {
        document.getElementById('actualform').classList.remove('hide');
        document.getElementById('botsettings_startsetup').classList.add('hide');
        document.getElementById('botsettings_startsetup_edit').classList.remove('hide');

        document.getElementById('Botlanguage').classList.add('hide');
        document.getElementById('Conversationstarter').classList.add('hide');
        document.getElementById('Bottrigger').classList.add('hide');
        document.getElementById('NoCustomerResponse').classList.add('hide');
      }
</script>

app/views/home/composemessage.html.erb
<%= render 'layouts/navbar_main'%>
<%= render 'layouts/navbar_navigation_composemessage'%>
<%= render 'layouts/messages'%>
<div style="overflow: auto;">
	<div class="container">
		<!-- main content -->
		<div class="row mt-4">
			<div class="rowheight_four col-12">
				<%= render 'home/edit/composemessage_main', parent_id: 0%>
			</div>
		</div>
	</div>
</div>

app/views/home/createbot_intro.html.erb
<%= render 'layouts/navbar'%>
<%= render 'layouts/messages'%>
<div class="container"  style="margin-top: 100px;">
	<div class="mx-auto mt-2 mb-4" style="width: 120px;">
		<%= image_tag('chatbot.JPG', size: "120", class: "rounded-circle")%>
	</div>
	<div id="intro_chat">
		<div class="mx-auto mb-1 hide smallfont" style="width: 75px;" id="first_message">
			<div class="shadow-sm p-3 mb-1 bg-white rounded text-center">
				Hi
			</div>
		</div>

		<div class="mx-auto mb-1 hide smallfont" style="width: 200px;" id="second_message">
			<div class="shadow-sm p-3 mb-1 bg-white rounded text-center">
				I am your Whatsapp chatbot
			</div>
		</div>

		<div class="mx-auto mb-1 hide smallfont" style="width: 300px;" id="third_message">
			<div class="shadow-sm p-3 mb-1 bg-white rounded text-center">
				I send and reply messages on your behalf
			</div>
		</div>

		<div class="mx-auto" style="width: 100px;" id="loading_symbol">
			<div class="shadow-sm p-3 mb-5 bg-white rounded text-center">
					<div class="spinner-grow text-secondary " style="width: 0.75rem; height: 0.75rem;" role="status">
				  		<span class="sr-only">Loading...</span>
					</div>
					<div class="spinner-grow text-secondary " style="width: 0.75rem; height: 0.75rem;" role="status">
				  		<span class="sr-only">Loading...</span>
					</div>
					<div class="spinner-grow text-secondary " style="width: 0.75rem; height: 0.75rem;" role="status">
				  		<span class="sr-only">Loading...</span>
					</div>
			</div>  
		</div>
	</div>
	
	<div class="hide mt-3" id="new_bot_name">
		<%= form_with scope: :bot, url: bots_path, method: :post,  local: true do |f| %>
			<div class=" mx-auto text-center" style="width: 300px;">
				<%= f.label :"Give me a name to continue", class: "col-form-label" %>
			</div>
			<div class="mx-auto text-center" style="width: 300px; " >
				<%= f.text_field :name, class: "formStyle", placeholder: "Give the bot a name" %> 
			</div>
			<div class="form-group mx-auto text-center mt-4" style="width: 300px;">
				<%= f.submit "Enter",value: "Enter", class: "btn createbotbutton"%>
			</div>				
		<% end %>
	</div>

</div>

<script type="text/javascript">
	// animation of chat messages in create bot
	setTimeout(function(){
       document.getElementById('loading_symbol').classList.add('hide');
       document.getElementById('first_message').classList.remove('hide');
      }, 2000);
      setTimeout(function(){
       document.getElementById('loading_symbol').classList.remove('hide');
      }, 2500);

      setTimeout(function(){
       document.getElementById('loading_symbol').classList.add('hide');
       document.getElementById('second_message').classList.remove('hide');
      }, 4000);

      setTimeout(function(){
       document.getElementById('loading_symbol').classList.remove('hide');
      }, 4500);

      setTimeout(function(){
       document.getElementById('loading_symbol').classList.add('hide');
       document.getElementById('third_message').classList.remove('hide');
       
       var div = document.getElementById("intro_chat");
       div.scrollTop = div.scrollHeight - div.clientHeight;
      }, 6000);

      setTimeout(function(){
       document.getElementById('new_bot_name').classList.remove('hide');
      }, 6500);
</script>

app/views/home/createbotedit.js.erb
document.getElementById('name_edit').classList.add('hide');
document.getElementById('name_update').classList.remove('hide');

app/views/home/createbotupdate.js.erb
// console.log('abba');
document.getElementById('name_edit').classList.remove('hide');
document.getElementById('name_update').classList.add('hide');
document.getElementById('name_edit_name').innerHTML = "<%= @bot.name%>";

app/views/home/selectbot.html.erb
<%= render 'layouts/navbar'%>
<%= render 'layouts/messages'%>
<div class="container">
	<div class="row">
		<div class="col-12">
			<div class="ml-4 row">
				<div class="col-2">
					<%= link_to '← Go Back', root_path, class: "custom_link"%>
				</div>
				<div class="col-6 text-center">
					<span class="p-2 ml-4 mt-4 grey heading">List of Bots</span>
				</div>
				<div class="col-4">
					
				</div>
			</div>
			<div class="box overflow_three">
				<table class="table table-bordered">
				  <thead>
				    <tr>
				      <th scope="col">S.no</th>
				      <th scope="col">Name</th>
				      <th scope="col" colspan="5" class="text-center">Options</th>
				      <th scope="col">Created</th>
				      <th scope="col">Updated</th>
				    </tr>
				  </thead> 
				  <tbody>
				  	<% i=0 %>
				  	<% for bot in Bot.all %>
				  	<%i=i+1%>
					    <tr>				    	
					      <td scope="row"><%= i%></td>
					      <td ><%= bot.name %></td>
					      <td><%= link_to 'Statistics', statistics_path(bot.id)%></td>
					      <td><%= link_to 'Test the bot', testbot_path(bot.id) %></td>
					      <td><%= link_to 'Edit', composemessage_path(bot.id)%></td>
					      <td><%= link_to 'Clone', root_path%></td>
					       <td><%= link_to 'Delete', bot_path(bot.id), method: :delete, data: {confirm: "Are you Sure do you want to delete this bot permanantly?"}%></td>
					      <td><%= time_ago_in_words(bot.created_at) %></td>
        				  <td><%= time_ago_in_words(bot.updated_at)%></td>
					    </tr>
				    <% end %>
				  </tbody>
				</table>
			</div>
			<div class="text-center mt-4" style="width: 100%;">
				<%= link_to '+ Add a new bot', createbot_intro_path, class: "btn bg-white"%>
			</div>
			
		</div>
	</div>
</div>

app/views/home/statistics.html.erb
<h1>Statistics Page</h1>
<%= @bot.name%>'s statistics

app/views/home/testbot.html.erb
<%= render 'layouts/navbar'%>
<%= render 'layouts/messages'%>
<div class="container">
	<div class="phonebackground mt-4 row", style="height: 530px;">
		<div class="col-6 shadow testcontent bg-white", style="height: 530px;">
			<div class="mt-2 mb-2 row">
				<div class="col-3">
					<%= link_to '← Go Back', root_path, class: "custom_link"%>
				</div>
				<div class="col-6">
					
				</div>
				<div class="col-3">
					<%= link_to 'Edit the Bot', composemessage_path(@bot.id), class: "custom_link"%>
				</div>
			</div>
			
			<div class="overflow_four">
				<table class="table table-bordered mt-2">
				  <thead>
				    <tr>
				      <th scope="col">Bot Parameter</th>
				      <th scope="col">Value</th>
				    </tr>
				  </thead>
				  <tbody>
				    <tr>
				      <th scope="row">Name:</th>
				      <td><%= @bot.name%>	</td>
				    </tr>
				    <tr>
				      <th scope="row">Phone Number:</th>
				      <td><%= @bot.phone%></td>
				    </tr>
				    <tr>
				      <th scope="row">Default Language:</th>
				      <td ><%= @bot.language%></td>
				    </tr>
				    <tr>
				      <th scope="row">Initiate conversation by:</th>
				      <td ><%= @bot.initconv%></td>
				    </tr>
				    <tr>
				      <th scope="row">Bot gets triggered by:</th>
				      <td ><%= @bot.triggerpoint%></td>
				    </tr>
				    <tr>
				      <th scope="row">Working Schedule:</th>
				      <td ><%= @bot.days%></td>
				    </tr>
				    <% if @bot.startdate%>
				    <tr>
				      <th scope="row">Start Date:</th>
				      <td ><%= @bot.startdate.to_date.to_formatted_s :long_ordinal %></td>
				    </tr>
				    <% end %>
				    <% if @bot.enddate%>
				    <tr>
				      <th scope="row">End Date:</th>
				      <td ><%= @bot.enddate.to_date.to_formatted_s :long_ordinal %></td>
				    </tr>
				    <% end %>
				    <tr>
				      <th scope="row">Start Time:</th>
				      <% if @bot.starttime %>
				      <td ><%= @bot.starttime.utc.strftime('%H:%M %p')%></td>
				      <% else %>
				      <td></td>
				      <% end %>
				    </tr>
				    <tr>
				      <th scope="row">End Time:</th>
				      <% if @bot.endtime %>
				      <td ><%= @bot.endtime.utc.strftime('%H:%M %p')%></td>
				      <% else %>
				      <td></td>
				      <% end %>
				    </tr>
				    <tr>
				      <th scope="row">Bot reboots in:</th>
				      <td ><%= @bot.rebootconv%> mins</td>
				    </tr>
				    <tr>
				      <th scope="row">Created at:</th>
				      <td ><%= time_ago_in_words(@bot.created_at) %></td>
				    </tr>
				    <tr>
				      <th scope="row">Updated at:</th>
				      <td ><%= time_ago_in_words(@bot.updated_at)%></td>
				    </tr>
				    <tr>
				      <th scope="row">Updated at:</th>
				      <td ><%= time_ago_in_words(@bot.updated_at)%></td>
				    </tr>
				  </tbody>
				</table>
			</div>
			
		</div>
		<div class="col-6">
			<%= render 'home/edit/test'%>
		</div>
		
	</div>	
</div>

app/views/home/welcome.html.erb
<%= render 'layouts/navbar'%>
<%= render 'layouts/messages'%>
<div class="container">
	<div class="row">
		<%= link_to '← Whatsapp Bot', root_path, class: "Whatsapp-Bot mt-4 mb-4"%>
	</div>
	<div class="row rowheight_two">
		<div class="col-5 shadow createbotdiv">
			<div class="mx-auto" style="width: 300px;">
				<div class="mx-auto mt-5" style="width: 300px;">
					<h1 class="whitetext text-center margintopcenter">Create Whatsapp Bot</h1>
				</div>
				<div class="mx-auto mt-4 whitetext_two text-center" style="width: 300px;">
					<p>Set up Business messages to send your clients automatically when they reach out to you</p>
				</div>
				<div class="mx-auto" style="width: 150px;">
					<%= link_to 'Create new Bot', createbot_intro_path, class: "btn btn-success"%>
				</div>
			</div>
		</div>
		<div class="col-7">
			<div class="container mt-2">
				<h5 class="mb-3">My Whatsapp bots</h5>
				<% if Bot.where(user_id: current_user.id).count != 0%>
				<div class="row mb-3 smallfont">
					<div class="col-3 text-center">
						Bot Name
					</div>
					<div class="col-3 text-center">
						Last Modified
					</div>
					<div class="col-3 text-center">
						Status
					</div>
					<div class="col-3 text-center">
						Action
					</div>
				</div>
				<%end%>
				<div style="height: 323px; overflow: auto;">
				<% number_of_bots = 0%>	
				<% for bot in Bot.where(user_id: current_user.id)%>
				<%number_of_bots = number_of_bots + 1 %>
				<div class="row mt-3 mb-3 bg-white botlist smallfont">
					<div class="col-3">
						<%= bot.name %>
					</div>
					<div class="col-3 text-center">
						<%= time_ago_in_words(bot.updated_at)%>
					</div>
					<div class="col-3 text-center">
						<span class="mr-2" id= <%= "update_active_toggle"+ (bot.id).to_s %> >
							<% if bot.active == true%>
								Active
							<% else%>
								Inactive
							<% end %>
						</span>
						<label class="switch my-auto">
						  <% if bot.active == true%>
						    <input type="checkbox" checked data-remote="true" class="slider round" data-method="put" data-url= <%= bot_active_path(bot.id)%>>
						  <% else %>
						  	<input type="checkbox" data-remote="true" class="slider round" data-method="put" data-url= <%= bot_active_path(bot.id)%>>
						  <% end %>
						  <span class="slider round"></span>
						</label>		
					</div>
					<div class="col-3 text-center">
						<%= link_to 'Edit', composemessage_path(bot.id), class: "btn btn-dark"%>

						<span class="dropdown">
							<button class="btn dropdown-toggle" type="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<%= image_tag("hamburger.png", size: "20" ) %>
							</button>
							<style>.dropdown-toggle::after { 
								content: none;
							    } 
							</style>
							<div class="dropdown-menu" style="width: 50px;">
							  	<%= link_to 'Statistics', statistics_path(bot.id), class: "dropdown-item" %> 
								<%= link_to 'Test the bot', testbot_path(bot.id), class: "dropdown-item"  %>
								<%= link_to 'Clone', root_path, class: "dropdown-item"%>  
                				<%= link_to 'Delete', bot_path(bot.id), method: :delete, data: { confirm: "Are you sure about deleting this bot. This is an irreversible action!" }, class: "dropdown-item delete_link"%>    
							</div>
						</span>
					</div>
				</div>
				<% end %>
				
				<%if number_of_bots == 0%>
					<div class="border text-center p-5">
						Please create the bots to see here.
					</div>
				<%end%>

				</div>
			</div>
		</div>
	</div>
</div>