config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  get '/createbot/intro', to: 'home#createbot_intro'
  get '/createbot/:id', to: 'home#createbotedit', as: 'createbotedit'
  put '/createbot/update/:id', to: 'home#createbotupdate', as: 'createbotupdate'
  get '/selectbot', to: 'home#selectbot'
  #bot editing part
  get '/botsettings/:id', to: 'home#botsettings', as: 'botsettings'
  get '/composemessage/:id', to: 'home#composemessage',as: 'composemessage'
  get '/activatebot/:id', to: 'home#activatebot', as: 'activatebot'
  #bot info part
  get '/statistics/:id', to: 'home#statistics', as: 'statistics'
  get '/testbot/:id', to: 'home#testbot', as: 'testbot'
  resources :bots
  post '/botsetting/reminders/:id', to:'active#botsettings_reminder_create', as:'botsettings_reminder_create'
  put '/botsetting/reminders/edit/:id', to:'active#botsettings_reminder_edit', as:'botsettings_reminder_edit'
  delete '/botsetting/reminders/delete/:id', to:'active#botsettings_reminder_delete', as:'botsettings_reminder_delete'
  put 'active/:id', to: 'active#updateactive', as: 'bot_active'
  #compose message
  get 'triggerphrase/edit/:id' , to: 'active#triggerphraseedit' , as: 'triggerphraseedit'
  get 'triggerphrase/confirm/:id' , to: 'active#triggerphraseconfirm' , as: 'triggerphraseconfirm'
  post 'triggerphrase/create/:id' , to: 'active#triggerphrasecreate' , as: 'triggerphrasecreate'
  delete 'triggerphrase/delete/:id/:botid' , to: 'active#triggerphrasedelete' , as: 'triggerphrasedelete'
  #nodes
  post 'nodes/create/:botid/:parentid/:nodetype' , to: 'nodes#create' , as: 'nodescreate'
  delete 'nodes/destroy/:id' , to: 'nodes#destroy' , as: 'nodes_destroy'
  post 'nodes/message_create' , to: 'nodes#message_create' , as: 'nodes_message_create'
  delete 'nodes/message_delete/:msg_id/:bot_id/:node_id', to: 'nodes#message_delete', as: 'nodes_message_delete'
  put 'nodes/update_options/:bot_id/:node_id', to: 'nodes#update', as: 'nodes_update_options'
  get 'nodes/expand/:bot_id/:node_id', to: 'nodes#expand', as: 'nodes_expand'
  get 'nodes/number_of_nodes_increment/:node_id', to: 'nodes#increment', as: 'number_of_nodes_increment'
  get 'nodes/number_of_nodes_decrement/:node_id', to: 'nodes#decrement', as: 'number_of_nodes_decrement'
  post 'nodes/add_numberof_nodes/:botid/:parentid/:nodetype', to: 'nodes#add_number_of_nodes', as: 'add_number_of_nodes'
  delete 'nodes/usermessage_node_delete/:id/:position', to: 'nodes#usermessage_node_delete', as: 'usermessage_node_delete'
  get 'nodes/define_nodes/:id', to: 'nodes#define_nodes', as: 'define_nodes'
  put 'nodes/usermessage_options_form/:id', to: 'nodes#usermessage_options_form', as: 'usermessage_options_form'
  get 'nodes/usermessage_name_edit/:id', to: 'nodes#usermessage_name_edit', as: 'usermessage_name_edit'
  put 'nodes/usermessage_name_update/:id', to: 'nodes#usermessage_name_update', as: 'usermessage_name_update'
  get 'nodes/botmessage_name_edit/:id', to: 'nodes#botmessage_name_edit', as: 'botmessage_name_edit'
  put 'nodes/botmessage_name_update/:id', to: 'nodes#botmessage_name_update', as: 'botmessage_name_update'
  get 'nodes/usermessage/expand/:id', to: 'nodes#usermessage_expand', as: 'usermessage_expand'
  post 'nodes/usermessage/messages_create', to: 'nodes#usermessage_messages_create', as: 'usermessage_messages_create'
  delete 'nodes/usermessage_message_delete/:msg_id/:bot_id/:node_id', to: 'nodes#usermessage_message_delete', as: 'usermessage_message_delete'
  put 'nodes/toggle_exit_message/:id', to: 'nodes#toggle_exit_message', as: 'toggle_exit_message'
  put 'nodes/toggle_transfer_to_agent_message/:id', to: 'nodes#toggle_transfer_to_agent_message', as: 'toggle_transfer_to_agent_message'
  post 'nodes/error_message_define_node', to: 'nodes#error_message_define_node', as: 'error_message_define_node'
  post 'nodes/error_node_message_save/:id/:message_id', to: 'nodes#error_node_message_save', as: 'error_node_message_save'
  get 'nodes/usermessage/error_message_expand_icon/:node_id', to: 'nodes#error_message_expand_icon', as: 'error_message_expand_icon'
  delete 'nodes/usermessage/error_message_attempt_delete/:message_id', to: 'nodes#error_message_attempt_delete', as: 'error_message_attempt_delete'
  get 'nodes/usermessage/error_node_save/:node_id', to: 'nodes#error_node_save', as: 'error_node_save'
  get 'nodes/usermessage/add_another_error_attempt/:node_id', to: 'nodes#error_node_add_another_error_attempt', as: 'error_node_add_another_error_attempt'
  get 'nodes/usermessage/error_node_editing_message/:message_id', to: 'nodes#error_node_editing_message', as: 'error_node_editing_message'
  get 'nodes/usermessage/error_node_delete_icon_for_new_attempt/:error_node_id', to: 'nodes#error_node_delete_icon_for_new_attempt', as:'error_node_delete_icon_for_new_attempt'
  post 'nodes/botresponse/nodes_message_attach_media', to: 'nodes#nodes_message_attach_media', as: 'nodes_message_attach_media'
  get 'nodes/botresponse/add_a_new_text_message_button/:node_id', to: 'nodes#add_a_new_text_message_button', as:'add_a_new_text_message_button'
  post 'nodes/botresponse/nodes_message_attach_media_video', to: 'nodes#nodes_message_attach_media_video', as:'nodes_message_attach_media_video'
  post 'nodes/botresponse/nodes_message_attach_media_pdf', to: 'nodes#nodes_message_attach_media_pdf', as:'nodes_message_attach_media_pdf'
  get 'nodes/ckeditor/text_messages/edit_icon/:node_id/:bot_id/:message_id', to:'nodes#ckeditor_text_messages_edit_icon', as: 'ckeditor_text_messages_edit_icon'
  post 'nodes/ckeditor/text_messages/update/:node_id/:bot_id/:message_id', to: 'nodes#ckeditor_text_messages_update', as: 'ckeditor_text_messages_update'
  get 'nodes/ckeditor/nodes_message_delete_text_area/:node_id', to: 'nodes#nodes_message_delete_text_area', as: 'nodes_message_delete_text_area'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def landing
	end
	
	def welcome
	end

	def createbot_intro
	end

	def createbotedit
		@id = params[:id]
		@bot = Bot.find_by(id: @id)
		respond_to do |format|
			format.js
		end
	end


	def createbotupdate
		@id = params[:id]
		@bot = Bot.find_by(id: @id)
		@bot.update(params.require(:bot).permit(:name))
	 	respond_to do |format|
			format.js
		end
	end

	def selectbot
	end

	def botsettings
		@id = params[:id]
		@bot = Bot.find_by(id: @id)
		@userbots= Bot.where(user_id: current_user.id)
	end

	def composemessage
		@id = params[:id]
		@bot = Bot.find(@id)
		
	end

	def activatebot
		@id = params[:id]
		@bot = Bot.find(@id)
	end

	def statistics
		@id = params[:id]
		@bot = Bot.find(@id)
	end
	
	def testbot
		@id = params[:id]
		@bot = Bot.find(@id)
	end
end

app/views/home/edit/_activatebot_main.html.erb
<%= @bot.name%>

app/views/home/edit/_botresponse_and_usermessage_loop.html.erb
<% botmessagesmain_partial = "botmessagesmain_partial_" + (parent_id).to_s%>
<% usermessagemain_partial_with_connector = "usermessagemain_partial_with_connector_" + (parent_id).to_s%>

<div id="<%= botmessagesmain_partial %>">
	<%= render 'home/edit/nodes/botmessagesmain', parent_id: parent_id%>	
</div>

<div class="ml-3", id="<%= usermessagemain_partial_with_connector %>", style="margin-left: 0px;">
	<%= render 'home/edit/nodes/usermessagesmain_with_connector'%>	
</div>

app/views/home/edit/_botsettings_botlanguage.html.erb
<span style = "color: #7e7e7e"  class = "">Bot language</span>

<%= link_to " Change", root_path, method: :get,id: 'change_link_botlanguage',style: "margin-left: 46%; color: #157e4b; font-weight: 500; text-decoration: none", remote: true %> 
<%= @bot.language %>

app/views/home/edit/_botsettings_bottrigger.html.erb
<span style = "color: #7e7e7e;" >Bot trigger</span>

<span id="change_link_botrigger" style="margin-left: 51.15%; color: #157e4b; font-weight: 500; text-decoration: none; cursor: pointer;">Change</span>

<div class = " row mb-2 ml-0">
    <%if @bot.initconv == "Bot"%>
        <div class="col-9" style="margin-left: -15px; ">     
            Bot will start the conversation
        </div> 
    <%else%>
        <% if @bot.triggerpoint == "Default" %>
            <div class="col-9" style="margin-left: -15px; ">     
                Any message will trigger the bot
            </div>    
        <% end %> 

        <% if @bot.triggerpoint == "Trigger" %>
            <% if Triggerphrase.where(bot_id: @bot.id) == [] %>
                No triggerphrases are added.
            <% end %>  
            <% names = "" %>
                <% for phrase in Triggerphrase.where(bot_id: @bot.id)%>
                    <% names.concat(phrase.triggerphrase + ", ") %>
                <% end %> 
            <%= names.truncate(29) %>       
        <% end %>
    <%end%>    

</div>

<script type="text/javascript">
    <%if @bot.initconv == "Bot"%>
        document.getElementById('change_link_botrigger').style.color = "grey";
        document.getElementById('change_link_botrigger').style.cursor = "no-drop";
    <%end%>
</script>

app/views/home/edit/_botsettings_conversationstarter.html.erb
<span style = "color: #7e7e7e">Conversation Starter</span>

<%= link_to " Change", root_path, method: :get,id: 'change_link_conversation_starter',style: "margin-left: 30%; color: #157e4b; font-weight: 500; text-decoration: none" , remote: true %>
<%= @bot.initconv %>

app/views/home/edit/_botsettings_form_conv_starter.html.erb
<div style = " padding-top: 10%;">
	<div class = "mb-4 ml-0" >
		<h4>Who will initiate the conversation?</h4>	
	</div>		
	<%= form_with scope: :botsettingsstarter, url: bot_path(@bot.id), method: :put,  remote: true do |f| %>
		<%= f.text_field :Bot, value: "Bot", class: 'hide' %>
		<%= f.text_field :Customer, value: "Customer", class: 'hide' %>
		<%=  button_tag(value: "Customer", id: "Customer", type: 'submit', class: "container shadow button-bot-settings ml-3 mt-1 text-center", style: "width: auto; padding-top: 6px; padding-bottom: 6px;", remote: true ) do %>	
				Customer	
		<% end %>
		<%=  button_tag(value: "Bot", id: "Bot", type: 'submit', class: "container shadow button-bot-settings ml-3 mt-0", style: "width: auto; padding-top: 6px; padding-bottom: 6px;", remote: true, data:( @bot.triggerpoint != nil ? {confirm: "If any triggerphrases have been added, they will be deleted if bot starts the conversation"} : nil) ) do %>	
				Bot
		<% end %>
		<div class = "ml-3 mt-4">
		<strong>Note</strong>
		</div>
		<div class = "ml-3">
		If bot initiates message, it can send only Whatsapp approved templates.
		</div>
		<% if @bot.initconv != nil %>
			<% if @bot.initconv  == "Customer"%>
				<style>
					.button-bot-settings[type="submit"][id="Customer"][value="Customer"]{
						box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.12);
						border: solid 1px #00b15c;
						background-color: #deffef;
					};
				</style>
			<% end %>
			<% if @bot.initconv  == "Bot"%>
				<style>
					.button-bot-settings[type="submit"][id="Bot"][value="Bot"]{
						box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.12);
						border: solid 1px #00b15c;
						background-color: #deffef;
					};
				</style>
			<% end %>
		<% end %>	
	<% end %>
</div>

<script type="text/javascript">
	document.getElementById('Customer').onclick = function(){
		document.getElementById('botsettings_conv_starter_partial').classList.add('hide');
		document.getElementById('botsettings_trigger_phrases_partial').classList.remove('hide');
	}
	document.getElementById('Bot').onclick = function(){

		document.getElementById('botsettings_conv_starter_partial').classList.add('hide');
		document.getElementById('botsettings_want_reminder_partial').classList.remove('hide');
		document.getElementById('change_link_botrigger').style.color = "grey";
		document.getElementById('change_link_botrigger').style.cursor = "no-drop";
		document.getElementById('NoCustomerResponse').classList.remove('hide');

	}
</script>

app/views/home/edit/_botsettings_form_language.html.erb
<div style = "padding-top: 10%; ">
	<div class = "mb-4" >
		<h4>Select default bot language</h4>
	</div>		
	<%= form_with scope: :botsettingslanguage, url: bot_path(@bot.id), method: :put,  remote: true do |f| %>
		<div class = "ml-0 mt-4">
			<%= f.text_field :English, value: "English", class: 'hide' %>
			<%= f.text_field :Hindi, value: "Hindi", class: 'hide' %>
			<%= f.text_field :Tamil, value: "Tamil", class: 'hide' %>
			<%=  button_tag(value: "English",id: "English" ,type: 'submit', class: "container shadow button-bot-settings ml-3 mt-0", style: "width: auto; padding-top: 6px; padding-bottom: 6px;", remote: true ) do %>	
					English
			<% end %>
			<%=  button_tag(value: "Hindi", id: "Hindi",type: 'submit', class: "container shadow button-bot-settings ml-3 mt-1 text-center", style: "width: auto; padding-top: 6px; padding-bottom: 6px;", remote: true ) do %>	
					Hindi	
			<% end %>	
			<%=  button_tag(value: "Tamil", id: "Tamil", type: 'submit', class: "container shadow button-bot-settings ml-3 mt-1 text-center", style: "width: auto; padding-top: 6px; padding-bottom: 6px;", remote: true ) do %>	
					Tamil	
			<% end %>	
		</div>
	<% end %>
	<% if @bot.language != nil %>
	    <% if @bot.language == "English"%>
			<style>
			    .button-bot-settings[type="submit"][id="English"][value="English"]{
					box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.12);
					border: solid 1px #00b15c;
					background-color: #deffef;
				};
			</style>
		<% end %>
		<% if @bot.language == "Hindi"%>
			<style>
			    .button-bot-settings[type="submit"][id="Hindi"][value="Hindi"]{
					box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.12);
					border: solid 1px #00b15c;
					background-color: #deffef;
				};
			</style>
		<% end %>
		<% if @bot.language == "Tamil"%>
			<style>
			    .button-bot-settings[type="submit"][id="Tamil"][value="Tamil"]{
					box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.12);
					border: solid 1px #00b15c;
					background-color: #deffef;
				};
			</style>
		<% end %>
	<% end %>
</div>

<script type="text/javascript">
	document.getElementById('English').onclick = function(){
		document.getElementById('botsettings_language_partial').classList.add('hide');
		document.getElementById('botsettings_conv_starter_partial').classList.remove('hide');
	}
	document.getElementById('Hindi').onclick = function(){
		document.getElementById('botsettings_language_partial').classList.add('hide');
		document.getElementById('botsettings_conv_starter_partial').classList.remove('hide');
	}
	document.getElementById('Tamil').onclick = function(){
		document.getElementById('botsettings_language_partial').classList.add('hide');
		document.getElementById('botsettings_conv_starter_partial').classList.remove('hide');
	}
</script>

app/views/home/edit/_botsettings_form_specific_key_words.html.erb
<div style="margin-top: 30px; margin-bottom: 30px;">
	<% space = 0 %>
	<% for phrase in Triggerphrase.where(bot_id: @bot.id)%>
		<% space = space + 1 %>
		<span class="triggerphrase-botsettings ml-3 mr-1 p-2">
		    <span class= "ml-2 mr-2"><%= phrase.triggerphrase %>
		        <span class="mb-4 ml-2">
		        <%= link_to image_tag('deleteicon.png', size: "10"), triggerphrasedelete_path(phrase.id,@bot.id), method: :delete ,remote: true, class: "mr-2"%>
		        </span>		
		    </span>	
		</span>

		<% if space%3 == 0  %>
		  <br><br>
		<% end %>
	<% end %>	
</div>

app/views/home/edit/_botsettings_form_trigger_phrases.html.erb
<div style = "padding-top: 10%;">
   <div style = "">
		<%= form_with scope: :botsettingstrigger, url: bot_path(@bot.id), method: :put,  remote: true do |f| %>
			<div class = "mb-4" >
				<h4>Add keywords to which the bot will respond</h4>	
				<%= f.text_field :Default, value: "Default", class: 'hide' %>
				<%= f.text_field :Trigger, value: "Trigger", class: 'hide' %>
				<%=  button_tag(value: "Default", id: "Default", type: 'submit', class: "container shadow button-bot-settings mt-4", style: "width: auto; padding-top: 6px; padding-bottom: 6px;", remote: true, data:{confirm: "If there are any triggerphrases added by you for this bot, then all the triggerphrases will be deleted if this is made into a default bot."} ) do %>	
						Any keyword (Default bot)
				<% end %>
				<%=  button_tag(value: "Trigger",id: "Trigger", type: 'submit', class: "container shadow button-bot-settings ml-3 mt-4 text-center", style: "width: auto; padding-top: 6px; padding-bottom: 6px;", remote: true ) do %>	
						Specific keywords (Triggered bot)	
				<% end %>		
			</div>	
		<% end %>

		<% if @bot.triggerpoint != nil %>
			<% if @bot.triggerpoint  == "Default"%>
				<style>
					.button-bot-settings[type="submit"][id="Default"][value="Default"]{
						box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.12);
						border: solid 1px #00b15c;
						background-color: #deffef;
					};
				</style>
			<% end %>
			<% if @bot.triggerpoint  == "Trigger"%>
				<style>
					.button-bot-settings[type="submit"][id="Trigger"][value="Trigger"]{
						box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.12);
						border: solid 1px #00b15c;
						background-color: #deffef;
					};
				</style>
			<% end %>
		<% end %>


		<div id = "botsettings_trigger" style="overflow-y: auto; overflow-x: hidden; max-height: 120px;">
			<%= render 'home/edit/botsettings_form_specific_key_words' %>
		</div>

		<div id = "triggered_bot" class="hide">
			<div class="text-center mb-1" style = "margin-top: 2%;">
				<%= form_with scope: :botsettings_triggerphrase, url: triggerphrasecreate_path(@bot.id), method: :post, remote: true do |f| %>
					<div class = "row mt-4">
						<div class = " col-4 text-left ml-4 mr-0 p-0">
							<%= f.text_field :triggerphrase, class: "text-left form_trigger_input_bot_settings",id: 'botsettings_add_triggerphrase_text_field', placeholder:  "Add trigger words", style: "width: 250px; padding-left: 5px;"%> 
						</div>
						<div class = "col-1 text-right ml-0 mb-0 form_trigger_input_bot_settings" , style= "padding-bottom: 0px;" >
							<%= f.submit "Add", class: "submit-text_bot_settings", remote: true %>
						</div>
					</div>	
					<!-- settings_change_path(@bot.id, "reminder") -->
					<%= link_to " Next", root_path, id: "Next_button", method: :get, class: "btn btn-success ml-4", style: "margin-right: 10px; margin-top: -68px;",remote: true %>
				<% end %>
			</div>
		</div>

	</div>	
</div>

<script type="text/javascript">
	<%if Triggerphrase.where(bot_id: @bot.id) == []%>
		document.getElementById('Next_button').classList.add('hide');
	<%else%>
		document.getElementById('Next_button').classList.remove('hide');
	<%end%>

	<%if @bot.triggerpoint == "Trigger"%>
		document.getElementById('triggered_bot').classList.remove('hide');
	<%end%>
	document.getElementById('Trigger').onclick = function(){
		document.getElementById('triggered_bot').classList.remove('hide');
		document.getElementById('Trigger').style.boxShadow = "0 0 10px 0 rgba(0, 0, 0, 0.12)";
		document.getElementById('Trigger').style.border = "solid 1px #00b15c";
		document.getElementById('Trigger').style.backgroundColor = "#deffef";
		document.getElementById('Default').style.border = "solid 1px grey";
		document.getElementById('Default').style.backgroundColor = "white";
		
	}
	document.getElementById('Default').onclick = function(){
		document.getElementById('botsettings_want_reminder_partial').classList.remove('hide');
		document.getElementById('botsettings_trigger_phrases_partial').classList.add('hide');
	}
	document.getElementById('Next_button').onclick = function(){
		document.getElementById('botsettings_want_reminder_partial').classList.remove('hide');
		document.getElementById('botsettings_trigger_phrases_partial').classList.add('hide');
	}		
</script>

app/views/home/edit/_botsettings_form_want_reminder.html.erb
<div class = " mb-4">
	<h4>Send reminder message if the customer doesn't respond?</h4>	
	<%= form_with scope: :botsettingssetreminder, url: bot_path(@bot.id), method: :put, remote: true do |f| %>
		<%= f.text_field :no, value: "no", class: 'hide' %>
		<%= f.text_field :yes, value: "yes", class: 'hide' %>
		<%=  button_tag(value: "yes",id: "yes", type: 'submit', class: "mt-4 ml-0", style: "margin-right: 20px; border: none; background-color: #f7f2ed", remote: true ) do %>	
				Yes, Set reminder >
		<% end %>
		
		<div>
			<%=  button_tag(value: "no",id: "no", type: 'submit', class: "hide btn btn-success mt-4 ml-0", style: "margin-right: 20px;", remote: true ) do %>	
					Skip this for now
			<% end %>
		</div>
		
		<div class="hide" id="you_skipped_this_step">
			&nbsp;(You skipped this step earlier. If you want, you can add the reminders now.)
		</div>	
		<div style = "margin-right: 300px;">
			<%=  button_tag(value: "no",id: "no_duplicate", type: 'submit', class: "hide btn btn-success mt-4 ml-0", remote: true ) do %>	
					Skip this step
			<% end %>
		</div>	
				
	<% end %>
</div>

<script type="text/javascript">
	<% if @bot.reminder == nil %>
		document.getElementById('no').classList.remove('hide');
	<% end %>

	<% if @bot.reminder != nil %>
		<% if @bot.reminder == "no" %>
			document.getElementById('no_duplicate').classList.remove('hide');
			document.getElementById('you_skipped_this_step').classList.remove('hide');
		<% end %>
	<% end %>

	document.getElementById('yes').onclick = function(){
		document.getElementById('botsettings_want_reminder_partial').classList.add('hide');
		document.getElementById('botsettings_reminder_partial').classList.remove('hide');
	}
	document.getElementById('no').onclick = function(){
		document.getElementById('botsettings_want_reminder_partial').classList.add('hide');
		document.getElementById('botsettings_setup_partial').classList.remove('hide');
	}
	if (document.getElementById('no_duplicate')){
		document.getElementById('no_duplicate').onclick = function(){
			document.getElementById('botsettings_want_reminder_partial').classList.add('hide');
			document.getElementById('botsettings_setup_partial').classList.remove('hide');
		}
	}

</script>

app/views/home/edit/_botsettings_noCustomerResponse.html.erb
<span style = "color: #7e7e7e;" >When no customer response</span>

<%= link_to " Change", root_path, method: :get,id: 'change_link_no_customer_response',style: "margin-left: 11.25%; color: #157e4b; font-weight: 500; text-decoration: none;" , remote: true %>

<% i =1 %>
<div class = "mb-4 ml-0 p-0 container" style = "height: 70px; overflow-y: auto;" id = "style-4">
    <% for reminder in Reminder.where(bot_id: @bot.id)%>
        <%= "Reminder " + i.to_s() + "- "+ reminder.reminder %>	
        <br>
        <% i = i + 1 %>
    <% end %>
    <% if Reminder.where(bot_id: @bot.id) == [] %>
        <span style = "color: #FF8C00;">Not Defined</span><%= image_tag('warning.png', size: "25", class: "mb-2") %>
    <% end %>      
</div>

app/views/home/edit/_botsettings_startsetup_edit.html.erb
<div class="container">
	<h3 class = "botsettings_heading">Bot Settings</h3>
    <div class = "mt-4">
        <div id = "Outgoingnumber" class = "mb-3">
            <%=  render 'home/edit/botsettings_outgoingnumber' %>
        </div>
        <div id = "Botlanguage" class = "mb-3">
           <%= render 'home/edit/botsettings_botlanguage' %>
        </div> 
        <div  id = "Conversationstarter" class = "mb-3">    
            <%= render 'home/edit/botsettings_conversationstarter' %>
        </div>  
        <div  id = "Bottrigger" class = "mb-3"> 
            <%= render 'home/edit/botsettings_bottrigger' %>
        </div>  
        <div  id = "NoCustomerResponse" class = "mt-0">   
           <%= render 'home/edit/botsettings_noCustomerResponse' %>
        </div>    
    </div>  
</div>

<script type="text/javascript">
    <%if @bot.language == nil %>
        document.getElementById('Botlanguage').classList.add('hide');
    <%end%>
    <%if @bot.initconv == nil %>
        document.getElementById('Conversationstarter').classList.add('hide');
    <%end%>
    <%if @bot.triggerpoint == nil %>
        document.getElementById('Bottrigger').classList.add('hide');
    <%end%>
    <%if @bot.reminder == nil %>
        document.getElementById('NoCustomerResponse').classList.add('hide');
    <%end%>
</script>

app/views/home/edit/_test.html.erb
<div class="whatsapphead p-2", style="height: 50px; width: 235px;">
	<%= link_to '←', root_path, class: "mr-2 whatsappbackbutton"%>
	<%= image_tag('chatbot.JPG', size: "30", class: "rounded-circle mr-1")%>
	<%= @bot.name%>
</div>
<div class="whatsappbody", style="height: 450px; width: 235px;">
	<div class="whatsapprecievemessage", style="height: 400px; width: 235px;">
		
	</div>
	<div class="whatsappsendmessage", style="height: 50px; width: 235px;">
		<%= form_with scope: :test, url: root_path, method: :post,  local: true do |f| %>
			<div class="row">
				<div class="form-group col-9 ml-2">
					<%= f.text_area :user_test_message, class: "form-control shadow sendmessage", size: "1x1" %> 
				</div>
				<% if @bot%>
					<%= f.hidden_field :bot_id, value: @bot.id %>
				<% end %>
				<% if current_user%>
					<%= f.hidden_field :user_id, value: current_user.id %>
				<% end %>
				<div class="form-group col-2">
					<%= f.submit value: "", class: "btn send "%>
				</div>
			</div>	
		<% end %>
	</div>
</div>