config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  get '/createbot/intro', to: 'home#createbot_intro'
  get '/createbot/:id', to: 'home#createbotedit', as: 'createbotedit'
  put '/createbot/update/:id', to: 'home#createbotupdate', as: 'createbotupdate'
  get '/selectbot', to: 'home#selectbot'
  #bot editing part
  get '/botsettings/:id', to: 'home#botsettings', as: 'botsettings'
  get '/composemessage/:id', to: 'home#composemessage',as: 'composemessage'
  get '/activatebot/:id', to: 'home#activatebot', as: 'activatebot'
  #bot info part
  get '/statistics/:id', to: 'home#statistics', as: 'statistics'
  get '/testbot/:id', to: 'home#testbot', as: 'testbot'
  resources :bots
  post '/botsetting/reminders/:id', to:'active#botsettings_reminder_create', as:'botsettings_reminder_create'
  put '/botsetting/reminders/edit/:id', to:'active#botsettings_reminder_edit', as:'botsettings_reminder_edit'
  delete '/botsetting/reminders/delete/:id', to:'active#botsettings_reminder_delete', as:'botsettings_reminder_delete'
  put 'active/:id', to: 'active#updateactive', as: 'bot_active'
  #compose message
  get 'triggerphrase/edit/:id' , to: 'active#triggerphraseedit' , as: 'triggerphraseedit'
  get 'triggerphrase/confirm/:id' , to: 'active#triggerphraseconfirm' , as: 'triggerphraseconfirm'
  post 'triggerphrase/create/:id' , to: 'active#triggerphrasecreate' , as: 'triggerphrasecreate'
  delete 'triggerphrase/delete/:id/:botid' , to: 'active#triggerphrasedelete' , as: 'triggerphrasedelete'
  #nodes
  post 'nodes/create/:botid/:parentid/:nodetype' , to: 'nodes#create' , as: 'nodescreate'
  delete 'nodes/destroy/:id' , to: 'nodes#destroy' , as: 'nodes_destroy'
  post 'nodes/message_create' , to: 'nodes#message_create' , as: 'nodes_message_create'
  delete 'nodes/message_delete/:msg_id/:bot_id/:node_id', to: 'nodes#message_delete', as: 'nodes_message_delete'
  put 'nodes/update_options/:bot_id/:node_id', to: 'nodes#update', as: 'nodes_update_options'
  get 'nodes/expand/:bot_id/:node_id', to: 'nodes#expand', as: 'nodes_expand'
  get 'nodes/number_of_nodes_increment/:node_id', to: 'nodes#increment', as: 'number_of_nodes_increment'
  get 'nodes/number_of_nodes_decrement/:node_id', to: 'nodes#decrement', as: 'number_of_nodes_decrement'
  post 'nodes/add_numberof_nodes/:botid/:parentid/:nodetype', to: 'nodes#add_number_of_nodes', as: 'add_number_of_nodes'
  delete 'nodes/usermessage_node_delete/:id/:position', to: 'nodes#usermessage_node_delete', as: 'usermessage_node_delete'
  get 'nodes/define_nodes/:id', to: 'nodes#define_nodes', as: 'define_nodes'
  put 'nodes/usermessage_options_form/:id', to: 'nodes#usermessage_options_form', as: 'usermessage_options_form'
  get 'nodes/usermessage_name_edit/:id', to: 'nodes#usermessage_name_edit', as: 'usermessage_name_edit'
  put 'nodes/usermessage_name_update/:id', to: 'nodes#usermessage_name_update', as: 'usermessage_name_update'
  get 'nodes/botmessage_name_edit/:id', to: 'nodes#botmessage_name_edit', as: 'botmessage_name_edit'
  put 'nodes/botmessage_name_update/:id', to: 'nodes#botmessage_name_update', as: 'botmessage_name_update'
  get 'nodes/usermessage/expand/:id', to: 'nodes#usermessage_expand', as: 'usermessage_expand'
  post 'nodes/usermessage/messages_create', to: 'nodes#usermessage_messages_create', as: 'usermessage_messages_create'
  delete 'nodes/usermessage_message_delete/:msg_id/:bot_id/:node_id', to: 'nodes#usermessage_message_delete', as: 'usermessage_message_delete'
  put 'nodes/toggle_exit_message/:id', to: 'nodes#toggle_exit_message', as: 'toggle_exit_message'
  put 'nodes/toggle_transfer_to_agent_message/:id', to: 'nodes#toggle_transfer_to_agent_message', as: 'toggle_transfer_to_agent_message'
  post 'nodes/error_message_define_node', to: 'nodes#error_message_define_node', as: 'error_message_define_node'
  post 'nodes/error_node_message_save/:id/:message_id', to: 'nodes#error_node_message_save', as: 'error_node_message_save'
  get 'nodes/usermessage/error_message_expand_icon/:node_id', to: 'nodes#error_message_expand_icon', as: 'error_message_expand_icon'
  delete 'nodes/usermessage/error_message_attempt_delete/:message_id', to: 'nodes#error_message_attempt_delete', as: 'error_message_attempt_delete'
  get 'nodes/usermessage/error_node_save/:node_id', to: 'nodes#error_node_save', as: 'error_node_save'
  get 'nodes/usermessage/add_another_error_attempt/:node_id', to: 'nodes#error_node_add_another_error_attempt', as: 'error_node_add_another_error_attempt'
  get 'nodes/usermessage/error_node_editing_message/:message_id', to: 'nodes#error_node_editing_message', as: 'error_node_editing_message'
  get 'nodes/usermessage/error_node_delete_icon_for_new_attempt/:error_node_id', to: 'nodes#error_node_delete_icon_for_new_attempt', as:'error_node_delete_icon_for_new_attempt'
  post 'nodes/botresponse/nodes_message_attach_media', to: 'nodes#nodes_message_attach_media', as: 'nodes_message_attach_media'
  get 'nodes/botresponse/add_a_new_text_message_button/:node_id', to: 'nodes#add_a_new_text_message_button', as:'add_a_new_text_message_button'
  post 'nodes/botresponse/nodes_message_attach_media_video', to: 'nodes#nodes_message_attach_media_video', as:'nodes_message_attach_media_video'
  post 'nodes/botresponse/nodes_message_attach_media_pdf', to: 'nodes#nodes_message_attach_media_pdf', as:'nodes_message_attach_media_pdf'
  get 'nodes/ckeditor/text_messages/edit_icon/:node_id/:bot_id/:message_id', to:'nodes#ckeditor_text_messages_edit_icon', as: 'ckeditor_text_messages_edit_icon'
  post 'nodes/ckeditor/text_messages/update/:node_id/:bot_id/:message_id', to: 'nodes#ckeditor_text_messages_update', as: 'ckeditor_text_messages_update'
  get 'nodes/ckeditor/nodes_message_delete_text_area/:node_id', to: 'nodes#nodes_message_delete_text_area', as: 'nodes_message_delete_text_area'
end

app/views/layouts/_attach_messages.html.erb
<% if notice %>
	<div class='alert alert-success ml-2' style="width: 130px; height: 27px; font-size: 10px; padding: 2px; margin: 0;">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true" >&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger ml-2' style="width: 130px; height: 27px; font-size: 10px; padding: 2px; margin: 0;">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true" >&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %> 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'ReferralYogi', root_path, class:"navbar-brand"%>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!-- <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li> -->
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete%>
    </div>
  </div>
</nav>

app/views/layouts/_navbar_main.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <%= link_to ' ← ReferralYogi', root_path, class:"navbar-brand colomn_break pr-3"%> 

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item" id="name_edit">
        <%= image_tag('chatbot.JPG', size: "25", class: "rounded-circle mr-3")%>
        <span class= "whitetext_two mr-2" id="name_edit_name"><%= truncate(@bot.name, length: 15)%></span>
         <span><%= link_to image_tag('editicon.png', size: "12"), createbotedit_path(@bot.id), id: "name_edit_icon", remote: true%></span>
      </li>
      <li class="nav-item hide" id="name_update">
        <%= form_with scope: :bot, url: createbotupdate_path, method: :put, remote: true do |f| %>
          <span class="mx-auto text-center" style="width: 300px; " >
            <%= f.text_field :name, class: "editnamefield", value: @bot.name, remote: true%> 
          </span>
          <span class="form-group mx-auto text-center mt-4" style="width: 300px;">
            <%= f.submit value: "Update", class: "btn btn-sm createbotbutton", remote: true%>
          </span>
        <% end %>  
      </li>
      <!-- <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li> -->
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete%>
    </div>
  </div>
</nav>

app/views/layouts/_navbar_navigation_botsettings.html.erb
<nav class="mynavbar bg-white">
  <div class="row mr-0">
    <div class="col-8">
      <ul class="steps">
        <li class="past" style="width: 20px;">
          <span>
            <strong>Steps</strong>
          </span>
        </li>
        
        <li class="present">
          <span>
            <%= link_to botsettings_path(@bot.id), class:"navbar_custom_links" do%>
              <div style="height: 50px; width: 200px;">1. Bot Settings</div>
            <% end %>
          </span><i></i> 
        </li>  
        
        <li class="future">
          <span>
            <%= link_to composemessage_path(@bot.id), id: "compose_message_navbar_link",class:"navbar_custom_links" do%>
              <div style="height: 50px; width: 200px;">2. Bot Flow</div>
            <% end %>
          </span><i></i>
        </li>
      </ul>
    </div>

    <div class="col-2">
      
    </div>
    <div class="col-2 pr-0">
      <div class="text-center navbar_content_height_activate">
        Activate
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_navbar_navigation_composemessage.html.erb
<nav class="mynavbar bg-white">
  <div class="row mr-0">
    <div class="col-10">
      <ul class="steps">
        <li class="past" style="width: 20px;">
          <span>
            <strong>Steps</strong>
          </span>
        </li>
        <li class="future">
          <span>
            <%= link_to botsettings_path(@bot.id), class:"navbar_custom_links" do%>
              <div style="height: 50px; width: 200px;">1. Bot Settings</div>
            <% end %>
          </span><i></i>
        </li>
        <li class="present">
          <span>
            <%= link_to composemessage_path(@bot.id), class:"navbar_custom_links" do%>
              <div style="height: 50px; width: 200px;">2. Bot Flow</div>
            <% end %>
          </span><i></i>
        </li>
      </ul>
    </div>
    <div class="col-1 p-0">
      <div class="navbar_content_height_undo colomn_break_two text-center">
        <%= link_to testbot_path(@bot.id), class: "Undo" do%>
          <div style="height: 50px; width: 100px; font-size: 12px;">
            <%= image_tag('phoneicon.png', size: "12")%>
            Test the Bot
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-1 p-0">
      <div class="navbar_content_height_undo colomn_break_two text-center">
        <%= link_to root_path, class: "Undo" do%>
          <div style="height: 50px; width: 100px; font-size: 12px;">
            <%= image_tag('phoneicon.png', size: "12")%>
            Save & Close
          </div>
        <% end %>
      </div>
    </div>
    <!-- <div class="col-2 p-0">
      <div class="text-center navbar_content_height_activate">
        Activate
      </div>
    </div> -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UltimateChatBotBuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script type="text/javascript">
      
    </script>
  </body>
</html>